theme: jekyll-theme-time-machine
title: Hannah's Portfolio Homepage
description: A place to view my visualizations and projects!
include: ["custom.css"]

# Navigation Menu
header_pages:
  - index.md
  - DATA302/index.md
  - DATA303/index.md
  - about.md
  - contact.md
