theme: jekyll-theme-minimal
title: Hannah's Portfolio Homepage
description: A place to view my visualizations and projects!
include: ["custom.css"]

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: DATA302 Projects
    url: /DATA302
  - title: DATA303 Projects
    url: /DATA303
  - title: About Me
    url: /about
  - title: Contact
    url: /contact
